# This is a basic workflow that is manually triggered

name: 01a Hola miundo

on:
  push:
   branches:
     - main,
     - feature/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola mundo
      run: echo "Hola, Alberto"
