# This is a basic workflow that is manually triggered

name: 01b Hola miundo

on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola Alberto
      run: echo "Hola, Alberto"
