# This is a basic workflow that is manually triggered

name: 02 - Evento Issue

on:
  workflow_dispatch:
  issues:
    types: [opened]
  push:
    paths-ignore:
      - '**.md'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola issues
      run: echo "Hola, Alberto con issues"