# This is a basic workflow that is manually triggered

name: 04a - distintas shells

on:
  push:
    branches:
      - main
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bash
        shell: bash
        run: echo $0
      - name: sh
        shell: sh
        run: echo $0
      - name: Por defecto
        run: echo $0