name: 04b - instalar paquetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check Node.js version
        run: node --version
      - name: Install node and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
      - name: install jsolint
        run:
          sudo npm install -g jsonlint
      - name: lint json
        run: jsonlint package.json