name: 05b - Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  expresiones:
    runs-on: ubuntu-latest
    steps:
      - name: runner OS
        id: runnerOS
        run: echo "${{ runner.os }}"
      - name: runner Architecture
        id: runnerArch
        run: echo "${{ runner.arch }}"